name: Deploy to Render and Run Migrations

on:
  push:
    branches:
      - main  # O la rama que estés usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to Render
      run: |
        # Aquí va el comando para hacer el deploy a Render
        # Asegúrate de tener las variables de entorno configuradas correctamente
        git remote add render https://git@render.com/tu-repo.git
        git push render main

    - name: Run migrations on Render
      run: |
        # Ejecutar las migraciones en el entorno de Render
        source venv/bin/activate
        python manage.py migrate
